name: Testpage
favicon: null
layout_spectrum: 0.5176114023197442
typography_spectrum: 0.4439321702811867
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9666706731077284
  lightness: 0.8936509829945862
  saturation: 0.8672664279583842
  rhythmicContrast: 0.7604807009920478
purpose: []
